// This file is generated by SHA2017-badge/Firmware/ugfx/build_fonts.sh
#include "fonts/IBMPlexMono-Bold24.c"
#include "fonts/IBMPlexMono-Bold36.c"
#include "fonts/IBMPlexMono-Bold48.c"
#include "fonts/IBMPlexSans-Regular12.c"
#include "fonts/IBMPlexSans-Regular18.c"
#include "fonts/IBMPlexSans-Regular22.c"
